# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK5UffXVLSQ2zQx41DHXT_hBZgD9kBIS
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print(df.columns.tolist())

# STEP 3: Understand the Dataset

print("First 5 Rows:")
display(df.head())

print("\nData Types:")
print(df.dtypes)

# STEP 4: Check Missing Values

print("Missing Values in Each Column:")
print(df.isnull().sum())

# STEP 5: Check Duplicate Rows

duplicate_count = df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_count)

df = df.drop_duplicates()

# STEP 6: Statistical Summary

df.describe()

# STEP 7: Check Target Column Distribution

print("Fraud Distribution:")
print(df["isFraud"].value_counts())

print("\nFraud Percentage:")
print(df["isFraud"].value_counts(normalize=True) * 100)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="isFraud", data=df)

plt.title("Fraud vs Non-Fraud Transactions")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("Number of Transactions")

plt.show()

# STEP 9: Transaction Type Distribution

print("Transaction Types:")
print(df["type"].value_counts())

# Visualization
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="type", data=df)

plt.title("Transaction Type Distribution")
plt.xlabel("Transaction Type")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.show()

# STEP 10: Amount Distribution

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.hist(df["amount"], bins=50)

plt.title("Transaction Amount Distribution")
plt.xlabel("Transaction Amount")
plt.ylabel("Number of Transactions")

plt.show()

# STEP 11: Box Plot for Amount

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(x=df["amount"])

plt.title("Box Plot of Transaction Amount")
plt.xlabel("Transaction Amount")

plt.show()

# STEP 12: Amount vs Fraud

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(x="isFraud", y="amount", data=df)

plt.title("Transaction Amount vs Fraud")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("Transaction Amount")

plt.show()

# STEP 13: Origin Account Balance Analysis

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.hist(df["oldbalanceOrg"], bins=50, alpha=0.5, label="Old Balance")
plt.hist(df["newbalanceOrig"], bins=50, alpha=0.5, label="New Balance")

plt.title("Origin Account Balance Distribution")
plt.xlabel("Balance")
plt.ylabel("Number of Transactions")
plt.legend()

plt.show()

# STEP 14: Origin Balance vs Fraud

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(
    x="isFraud",
    y="oldbalanceOrg",
    data=df
)

plt.title("Old Balance of Origin Account vs Fraud")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("Old Balance of Origin Account")

plt.show()

# STEP 15: New Balance of Origin Account vs Fraud

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(
    x="isFraud",
    y="newbalanceOrig",
    data=df
)

plt.title("New Balance of Origin Account vs Fraud")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("New Balance of Origin Account")

plt.show()

# STEP 16: Destination Account Balance Analysis

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.hist(df["oldbalanceDest"], bins=50, alpha=0.5, label="Old Balance")
plt.hist(df["newbalanceDest"], bins=50, alpha=0.5, label="New Balance")

plt.title("Destination Account Balance Distribution")
plt.xlabel("Destination Balance")
plt.ylabel("Number of Transactions")
plt.legend()

plt.show()

# STEP 17: Old Destination Balance vs Fraud

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(
    x="isFraud",
    y="oldbalanceDest",
    data=df
)

plt.title("Old Destination Balance vs Fraud")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("Old Balance of Destination Account")

plt.show()

# STEP 18: New Destination Balance vs Fraud

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sns.boxplot(
    x="isFraud",
    y="newbalanceDest",
    data=df
)

plt.title("New Destination Balance vs Fraud")
plt.xlabel("Fraud (0 = Not Fraud, 1 = Fraud)")
plt.ylabel("New Balance of Destination Account")

plt.show()

# STEP 19: Correlation Analysis

import seaborn as sns
import matplotlib.pyplot as plt

corr = df.corr(numeric_only=True)

plt.figure(figsize=(12, 8))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.show()

# STEP 20: Correlation with Target

target_corr = df.corr(numeric_only=True)["isFraud"].sort_values(
    ascending=False
)

print("Correlation with isFraud:")
print(target_corr)

# STEP 21: Check ID Columns

print("Sample nameOrig values:")
print(df["nameOrig"].head())

print("\nSample nameDest values:")
print(df["nameDest"].head())

print("\nUnique values:")
print("nameOrig:", df["nameOrig"].nunique())
print("nameDest:", df["nameDest"].nunique())

# STEP 22: Drop ID Columns

df = df.drop(["nameOrig", "nameDest"], axis=1)

print("Remaining columns:")
print(df.columns.tolist())

# STEP 23: Encode Transaction Type

df = pd.get_dummies(df, columns=["type"], dtype=int)

print("Columns after encoding:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

# STEP 24: Separate Features and Target

X = df.drop("isFraud", axis=1)
y = df["isFraud"]

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())

# STEP 25: Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# STEP 26: Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

# STEP 27: Train Logistic Regression

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

print("Logistic Regression model trained successfully!")

# STEP 28: Make Predictions

y_pred = model.predict(X_test_scaled)

print("First 20 Predictions:")
print(y_pred[:20])

# STEP 29: Model Evaluation

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

# STEP 30: Confusion Matrix

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Not Fraud", "Fraud"]
)

disp.plot()
plt.title("Confusion Matrix - Fraud Detection")
plt.show()

# STEP 31: Classification Report

from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Not Fraud", "Fraud"]
))

# STEP 32: ROC Curve and AUC

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Fraud probability
y_prob = model.predict_proba(X_test_scaled)[:, 1]

# ROC values
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# AUC
auc = roc_auc_score(y_test, y_prob)

print("AUC Score:", auc)

# Plot ROC Curve
plt.figure(figsize=(8, 6))

plt.plot(fpr, tpr, label=f"AUC = {auc:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Fraud Detection")
plt.legend()

plt.show()

# STEP 33: User Input Prediction

import pandas as pd

print("Enter Transaction Details")

step = float(input("Step: "))
amount = float(input("Amount: "))
oldbalanceOrg = float(input("Old Balance Origin: "))
newbalanceOrig = float(input("New Balance Origin: "))
oldbalanceDest = float(input("Old Balance Destination: "))
newbalanceDest = float(input("New Balance Destination: "))
isFlaggedFraud = int(input("Is Flagged Fraud (0/1): "))

print("\nTransaction Type:")
print("1 - CASH_IN")
print("2 - CASH_OUT")
print("3 - DEBIT")
print("4 - PAYMENT")
print("5 - TRANSFER")

transaction_type = int(input("Enter type number: "))

# Create input with same feature structure as X
new_data = pd.DataFrame(0, index=[0], columns=X.columns)

new_data["step"] = step
new_data["amount"] = amount
new_data["oldbalanceOrg"] = oldbalanceOrg
new_data["newbalanceOrig"] = newbalanceOrig
new_data["oldbalanceDest"] = oldbalanceDest
new_data["newbalanceDest"] = newbalanceDest
new_data["isFlaggedFraud"] = isFlaggedFraud

type_columns = {
    1: "type_CASH_IN",
    2: "type_CASH_OUT",
    3: "type_DEBIT",
    4: "type_PAYMENT",
    5: "type_TRANSFER"
}

new_data[type_columns[transaction_type]] = 1

# Scale the new input
new_data_scaled = scaler.transform(new_data)

# Prediction
prediction = model.predict(new_data_scaled)[0]
probability = model.predict_proba(new_data_scaled)[0][1]

if prediction == 1:
    print("\n🚨 Prediction: FRAUD")
else:
    print("\n✅ Prediction: NOT FRAUD")

print(f"Fraud Probability: {probability:.2%}")